Make compatible with Collaboration Kit
vaadin/kubernetes-kit pull request #90
Opened 2023-11-01 11:58 UTC by MatthewVaadin

## Description

As part of the work to allow Collaboration Kit to work with the Kubernetes Kit session serialization, it was found that K8s Kit has an issue when trying to determine if a bean has been defined for transient fields. If the class is just `Object`, Spring returns a prototype bean.

The pertinent change is in `SpringTransientHandler.java`. The rest of the changes are formatting and addressing code insight warnings.

## Type of change

- [X] Bugfix
- [ ] Feature

2023-11-02 10:13 UTC, heruan requested changes
Better to extract all the formatting changes to a separate PR, so we keep the relevant change on a clean commit.

2023-11-02 11:41 UTC, heruan commented on kubernetes-kit-demo/src/main/java/com/vaadin/kubernetes/demo/generator/DataGenerator.java
> +    public CommandLineRunner loadData(ContactRepository contactRepository,
Does this need to be public? Bean suppliers are usually kept private.

2023-11-02 11:41 UTC, heruan commented on kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/SerializationProperties.java
> +    TransientsProperties getTransients() {
Are we verifying that this is still discovered by Spring and reflected on the metadata for `.properties` files?

2023-11-03 07:07 UTC, mcollovati commented
I propose another little change related to `SpringTransientHandler`.
To prevent runtime errors, like the one with the `Object.class` bean detection resolved by this PR, The `matchesPrototype` method could check if the bean name effectively exists before calling `isPrototype` because the latter throws an exception if the bean is not defined.

```java
    private boolean matchesPrototype(String beanName, Object beanDefinition,
            Class<?> fieldValueType) {
        return appCtx.containsBean(beanName) && appCtx.isPrototype(beanName);
    }
```

In addition, as discussed with @MatthewVaadin, prototype beans may cause issues in deserialization:
for example, if there's a prototype `Consumer` bean registered and a class has a transient field of type `Consumer` that is however not injected (e.g. assigned a lambda in the constructor), the handler will potentially detect it as injectable and during deserialization inject an undesired object.
I wonder if we should remove the prototype detection or find a more precise way to detect if the field instance is really a prototype bean.

2023-11-08 10:16 UTC, merged